//
//  AccountTable.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class AccountTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _email: String?
    var _password: String?
    
    class func dynamoDBTableName() -> String {

        return "eetest-mobilehub-1780236080-AccountTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_email"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_password"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_email" : "email",
               "_password" : "password",
        ]
    }
}
