//
//  CustomIdTable.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class CustomIdTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _customId: String?
    var _userId: String?
    
    class func dynamoDBTableName() -> String {

        return "eetest-mobilehub-1780236080-CustomIdTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_customId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_customId" : "customId",
               "_userId" : "userId",
        ]
    }
}
