//
//  FilesTable.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class FilesTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _fileId: String?
    var _course: String?
    var _fileLink: String?
    var _name: String?
    var _timestamp: NSNumber?
    var _userId: String?
    
    class func dynamoDBTableName() -> String {

        return "eetest-mobilehub-1780236080-FilesTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_fileId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_fileId" : "fileId",
               "_course" : "course",
               "_fileLink" : "fileLink",
               "_name" : "name",
               "_timestamp" : "timestamp",
               "_userId" : "userId",
        ]
    }
}
