//
//  UserSubscribledList.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class UserSubscribledList: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _subsList: Set<String>?
    
    class func dynamoDBTableName() -> String {

        return "eetest-mobilehub-1780236080-UserSubscribledList"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_subsList" : "subsList",
        ]
    }
}
